[{"name": "test.test_reverse_dictionary.ReverseDictionary.test_first", "status": "errored", "message": "'liikuttaa'", "passed": false, "points": ["p01-13.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e13_reverse_dictionary/test/test_reverse_dictionary.py\", line 22, in test_first\n    self.assertEqual(r[\"liikuttaa\"], [\"move\"], msg=\"Incorrect translation of 'liikuttaa' for dict %s!\" % sd)\n"]}, {"name": "test.test_reverse_dictionary.ReverseDictionary.test_second", "status": "errored", "message": "'liikuttaa'", "passed": false, "points": ["p01-13.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e13_reverse_dictionary/test/test_reverse_dictionary.py\", line 31, in test_second\n    self.assertEqual(r[\"liikuttaa\"], [\"move\"], msg=\"Incorrect translation of 'liikuttaa' for dict %s!\" % sd)\n"]}]